steps:
  # 1. Create and use a buildx builder
  - name: gcr.io/cloud-builders/docker
    args:
      ['buildx',
        'create',
        '--name=multiarch',
        '--use'
      ]

  # Reservations
  - name: gcr.io/cloud-builders/docker
    id: build-and-push-reservations
    args:
      [
        "buildx",
        "build",
        "--platform=linux/amd64,linux/arm64",
        "-t",
        "asia-south1-docker.pkg.dev/sleepr-485709/reservations/production",
        "-f",
        "apps/reservations/Dockerfile",
        "--push",
        "."
      ]

  # Payments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/sleepr-485709/payments/production',
        '-f',
        'apps/payments/Dockerfile',
        '.'
      ]
    id: build-payments

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/sleepr-485709/payments/production'
      ]
    id: push-payments

  # Notifications
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/sleepr-485709/notifications/production',
        '-f',
        'apps/notifications/Dockerfile',
        '.'
      ]
    id: build-notifications

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/sleepr-485709/notifications/production'
      ]
    id: push-notifications

  # Auth
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/sleepr-485709/auth/production',
        '-f',
        'apps/auth/Dockerfile',
        '.'
      ]
    id: build-auth

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south1-docker.pkg.dev/sleepr-485709/auth/production'
      ]
    id: push-auth

serviceAccount: sleepr-sa@sleepr-485709.iam.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY
